#ifndef GAMEOFLIFE_CONFIGURATION_HPP
#define GAMEOFLIFE_CONFIGURATION_HPP

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define MAP_WIDTH 192
#define MAP_HEIGHT 108
#define CELL_WIDTH (int) (SCREEN_WIDTH / MAP_WIDTH)
#define CELL_HEIGHT (int) (SCREEN_HEIGHT / MAP_HEIGHT)
#define WAITING_TIME_MS 0

#define GOL GameOfLife

#endif //GAMEOFLIFE_CONFIGURATION_HPP
