#ifndef GAMEOFLIFE_CONFIGURATION_HPP
#define GAMEOFLIFE_CONFIGURATION_HPP

#define MAP_WIDTH 100
#define MAP_HEIGHT 100
#define CELL_WIDTH 8
#define WAITING_TIME_MS 0

#define GOL GameOfLife

#endif //GAMEOFLIFE_CONFIGURATION_HPP
