#ifndef GAMEOFLIFE_CONFIGURATION_HPP
#define GAMEOFLIFE_CONFIGURATION_HPP

#if 0
#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define MAP_WIDTH 192
#define MAP_HEIGHT 108
#define CELL_WIDTH (int) (SCREEN_WIDTH / MAP_WIDTH)
#define CELL_HEIGHT (int) (SCREEN_HEIGHT / MAP_HEIGHT)
#endif

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800
#define MAP_WIDTH 80
#define MAP_HEIGHT 80
#define CELL_WIDTH 10
#define CELL_HEIGHT 10

#define WAITING_TIME_MS 0

#define GOL GameOfLife

#endif //GAMEOFLIFE_CONFIGURATION_HPP
